# Site settings
# title appears in the header
title: Pascal Angst
# title-icon appears in the header to give some pizazz (leave blank for none)
title-icon:
# description, keywords, and image for meta tags
description: "Personal website"
keywords:
featured-image:
email: pascal.angst@unibas.ch

# author settings for cc-by, appears in the footer and credits
author: Pascal Angst
pub_year: 2022
github_username: pascalangst
twitter_username: pascalangst

# add the full url for the github repository
repo: "https://github.com/pascalangst/pascalangst.github.io"

# site urls
# add the url for the domain, 
url: https://pascalangst.github.io
# add subsection of the domain,
baseurl:

# add search box to footer?
search: true

# add google analytics if desired (optional)
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
